version: 0.0
os: linux
files:
  - source: web-tier/
    destination: /home/ec2-user/web-tier
  - source: nginx.conf
    destination: /etc/nginx/

permissions:
  - object: /home/ec2-user/web-tier
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      runas: root
